// Code generated by volcengine with private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package speechsaasprodiface provides an interface to enable mocking the SPEECH_SAAS_PROD service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package speechsaasprod20231107

import (
	"github.com/volcengine/volcengine-go-sdk/volcengine"
	"github.com/volcengine/volcengine-go-sdk/volcengine/request"
)

// SPEECHSAASPROD20231107API provides an interface to enable mocking the
// speechsaasprod.SPEECHSAASPROD20231107 service client's API operation,
//
//	// volcengine sdk func uses an SDK service client to make a request to
//	// SPEECH_SAAS_PROD.
//	func myFunc(svc SPEECHSAASPROD20231107API) bool {
//	    // Make svc.ActivateService request
//	}
//
//	func main() {
//	    sess := session.New()
//	    svc := speechsaasprod.New(sess)
//
//	    myFunc(svc)
//	}
type SPEECHSAASPROD20231107API interface {
	ListMegaTTSByOrderIDCommon(*map[string]interface{}) (*map[string]interface{}, error)
	ListMegaTTSByOrderIDCommonWithContext(volcengine.Context, *map[string]interface{}, ...request.Option) (*map[string]interface{}, error)
	ListMegaTTSByOrderIDCommonRequest(*map[string]interface{}) (*request.Request, *map[string]interface{})

	ListMegaTTSByOrderID(*ListMegaTTSByOrderIDInput) (*ListMegaTTSByOrderIDOutput, error)
	ListMegaTTSByOrderIDWithContext(volcengine.Context, *ListMegaTTSByOrderIDInput, ...request.Option) (*ListMegaTTSByOrderIDOutput, error)
	ListMegaTTSByOrderIDRequest(*ListMegaTTSByOrderIDInput) (*request.Request, *ListMegaTTSByOrderIDOutput)
}

var _ SPEECHSAASPROD20231107API = (*SPEECHSAASPROD20231107)(nil)
